{
    'name': 'PARC AUTO - SOTEC',
    'version': '1.0',
    'website': '',
    'category': 'Logiciel Parc Auto',
    'summary': "Ce logiciel est conçu pour faciliter la gestion de parc automobile",
    'author': 'Songo Technonogies (SOTEC)',
    'depends': ['base', 'fleet', "mail"],
    'images': ['static/description/auto.jpg'],
    'data': [
        'security/ir.model.access.csv',
        'views/parc_vue.xml',
        'views/parc_vue_histories.xml',
        'views/parc_vue_param_type_permis.xml',
        'views/parc_vue_param_chauffeur.xml',
        'views/parc_vue_param_employee.xml',
        'report/custom_header_footer.xml',
        'report/parc_report_parc_list.xml',
    ],
    'installable': True,
    'auto_install': False,
}
