{
    'name': 'TRANSPORT SONABHY - SOTEC',
    'version': '1.0',
    'website': '',
    'category': 'Logiciel AM',
    'summary': "Ce logiciel est conçu pour faciliter la gestion de la facturation SONABHY",
    'author': 'Songo Technonogies (SOTEC)',
    'depends': ['base',"mail"],
    'images': ['static/description/facturation.jpg'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/vue_facture.xml',
        'views/etat.xml',
        "Report/custom_header_footer.xml",
        "Report/report_comm.xml",
        "Report/report_approvisionnement.xml",
        "Report/report_facture.xml",
        "Report/report_facture_transit.xml",
        "Report/report_etat_quantite.xml",
        "Report/report_etat.xml",
        
    ],
    'installable': True,
    'auto_install': False,
}
